package com.wang.sysm.model;

import com.wang.sysm.model.base.BaseCodeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CodeLog extends BaseCodeLog<CodeLog> {
	public static final CodeLog dao = new CodeLog().dao();
}
