package com.wang.sysm.model;


import com.wang.sysm.model.base.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer().dao();
}
