package com.wang.sysm.model;


import com.wang.sysm.model.base.BaseTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test extends BaseTest<Test> {
	public static final Test dao = new Test().dao();
}
