package com.wang.sysm.model;


import com.wang.sysm.model.base.BaseTest2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Test2 extends BaseTest2<Test2> {
	public static final Test2 dao = new Test2().dao();
}
