package com.wang.sysm.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public M setId(String id) {
		set("id", id);
		return (M)this;
	}

	public String getId() {
		return getStr("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setContact(String contact) {
		set("contact", contact);
		return (M)this;
	}

	public String getContact() {
		return getStr("contact");
	}

	public M setTelephone(String telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public String getTelephone() {
		return getStr("telephone");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
